(define (problem Stack_11)
(:domain Stack)
(:objects table obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10)
(:init (on-table obj0)
(on-table obj1)
(on obj2 obj1)
(on-table obj3)
(on-table obj4)
(on obj5 obj3)
(on obj6 obj2)
(on obj7 obj6)
(on obj8 obj0)
(on obj9 obj5)
(on obj10 obj9)
(clear obj7)
(clear obj8)
(clear obj4)
(clear obj10))
(:goal (and (on-table obj0) (on-table obj1) (on-table obj2) (on-table obj3) (on-table obj4) (on-table obj5) (on-table obj6) (on-table obj7) (on-table obj8) (on-table obj9) (on-table obj10)))
)