(define (problem Stack_7)
(:domain Stack)
(:objects table obj0 obj1 obj2 obj3 obj4 obj5 obj6)
(:init (on-table obj0)
(on obj1 obj0)
(on-table obj2)
(on obj3 obj1)
(on obj4 obj3)
(on-table obj5)
(on obj6 obj2)
(clear obj4)
(clear obj5)
(clear obj6))
(:goal (and (on-table obj0) (on-table obj1) (on-table obj2) (on-table obj3) (on-table obj4) (on-table obj5) (on-table obj6)))
)