(define (problem Stack_6)
(:domain Stack)
(:objects table obj0 obj1 obj2 obj3 obj4 obj5)
(:init (on-table obj0)
(on-table obj1)
(on obj2 obj1)
(on obj3 obj0)
(on obj4 obj2)
(on obj5 obj3)
(clear obj4)
(clear obj5))
(:goal (and (on-table obj0) (on-table obj1) (on-table obj2) (on-table obj3) (on-table obj4) (on-table obj5)))
)