(define (problem Stack_4)
(:domain Stack)
(:objects table obj0 obj1 obj2 obj3)
(:init (on-table obj0)
(on-table obj1)
(on obj2 obj0)
(on-table obj3)
(clear obj1)
(clear obj2)
(clear obj3))
(:goal (and (on-table obj0) (on-table obj1) (on-table obj2) (on-table obj3)))
)