(define (problem Stack_10)
(:domain Stack)
(:objects table obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9)
(:init (on-table obj0)
(on-table obj1)
(on obj2 obj0)
(on obj3 obj2)
(on obj4 obj3)
(on-table obj5)
(on obj6 obj5)
(on obj7 obj4)
(on obj8 obj1)
(on-table obj9)
(clear obj7)
(clear obj8)
(clear obj6)
(clear obj9))
(:goal (and (on-table obj0) (on-table obj1) (on-table obj2) (on-table obj3) (on-table obj4) (on-table obj5) (on-table obj6) (on-table obj7) (on-table obj8) (on-table obj9)))
)