(define (problem Stack_3)
(:domain Stack)
(:objects table obj0 obj1 obj2)
(:init (on-table obj0)
(on-table obj1)
(on obj2 obj1)
(clear obj0)
(clear obj2))
(:goal (and (on-table obj0) (on-table obj1) (on-table obj2)))
)