(define (domain pr2-tamp)
	(:requirements :strips :equality)
	(:predicates
		(stackable ?o ?r)
		(grasp ?o ?g)
		(kin ?o ?p ?g ?t)
		(trajto ?o ?p ?t)
		(supported ?o ?p ?r)
		(target ?o)
		(nontarget ?o)
		(atpose ?o ?p)
		(atgrasp ?o ?g)
		(handempty )
		(safe_traj ?t)
		(traj_cfree ?t ?o ?p)
		(holding ?o)
		(attrajto ?t)
		(blockingtraj ?ob ?t)
		(= ?x ?y)
	)
	(:functions
	)
	(:action pick
		:parameters (?o ?p ?g ?t)
		:precondition (and (kin ?o ?p ?g ?t) (atpose ?o ?p) (handempty ) (safe_traj ?t))
		:effect (and (atgrasp ?o ?g) (not (atpose ?o ?p)) (not (handempty )))
	)
	(:action place
		:parameters (?o ?p ?g ?t)
		:precondition (and (kin ?o ?p ?g ?t) (atgrasp ?o ?g) (safe_traj ?t))
		:effect (and (atpose ?o ?p) (handempty ) (not (atgrasp ?o ?g)))
	)
	(:derived (holding ?o)
		(exists (?g) (and (grasp ?o ?g) (atgrasp ?o ?g)))
	)
	(:derived (safe_traj ?t)
		(forall (?o ?p) (or (not (atpose ?o ?p)) (traj_cfree ?t ?o ?p)))
	)
	(:derived (attrajto ?t)
		(exists (?p ?o) (and (atpose ?o ?p) (trajto ?o ?p ?t) (target ?o)))
	)
	(:derived (blockingtraj ?ob ?t)
		(forall (?pb) (and (attrajto ?t) (not (holding ?ob)) (or (not (atpose ?ob ?pb)) (not (traj_cfree ?t ?ob ?pb)))))
	)
)
