(define (domain pr2-tamp)
	(:requirements :strips :equality)
	(:predicates
		(controllable )
		(stackable ?o ?r)
		(table ?r)
		(grasp ?o ?g)
		(kin ?o ?p ?g ?q ?t)
		(basemotion ?q1 ?t ?q2)
		(armmotion ?q1 ?t ?q2)
		(supported ?o ?p ?r)
		(atpose ?o ?p)
		(atgrasp ?o ?g)
		(handempty )
		(atbconf ?q)
		(ataconf ?q)
		(traj_cfree ?t ?o ?p)
		(safe_traj ?t)
		(on ?o ?r)
		(holding ?o)
		(= ?x ?y)
	)
	(:functions
	)
	(:action pick
		:parameters (?o ?p ?g ?q ?t)
		:precondition (and (kin ?o ?p ?g ?q ?t) (atpose ?o ?p) (handempty ))
		:effect (and (atgrasp ?o ?g) (not (atpose ?o ?p)) (not (handempty )))
	)
	(:action place
		:parameters (?o ?p ?g ?q ?t)
		:precondition (and (kin ?o ?p ?g ?q ?t) (atgrasp ?o ?g) (not (handempty )))
		:effect (and (atpose ?o ?p) (not (atgrasp ?o ?g)) (handempty ))
	)
	(:derived (ontable ?o)
		(exists (?p) (and (supported ?o ?p ?r) (atpose ?o ?p) (table ?r)))
	)
	(:derived (on ?o ?r)
		(exists (?p) (and (supported ?o ?p ?r) (atpose ?o ?p)))
	)
	(:derived (holding ?o)
		(exists (?g) (and (grasp ?o ?g) (atgrasp ?o ?g)))
	)
)
