(define (problem Clutter_4)
(:domain clutter)
(:objects or1 ob0 ob1 ob2 ob3 rred rblue rtable)
(:init (on or1 rtable)
(block or1)
(red or1)
(on ob0 rtable)
(block ob0)
(blue ob0)
(on ob1 rtable)
(block ob1)
(blue ob1)
(on ob2 rtable)
(block ob2)
(blue ob2)
(on ob3 rtable)
(block ob3)
(blue ob3)
(table rtable)
(region rtable)
(hfree))
(:goal (and (holding or1)))
)