(define (problem Clutter_1)
(:domain clutter)
(:objects or1 ob0 rred rblue rtable)
(:init (on or1 rtable)
(block or1)
(red or1)
(on ob0 rtable)
(block ob0)
(blue ob0)
(table rtable)
(region rtable)
(hfree))
(:goal (and (holding or1)))
)