(define (problem Clutter_10)
(:domain clutter)
(:objects or1 ob0 ob1 ob2 ob3 ob4 ob5 ob6 ob7 ob8 ob9 rred rblue rtable)
(:init (on or1 rtable)
(block or1)
(red or1)
(on ob0 rtable)
(block ob0)
(blue ob0)
(on ob1 rtable)
(block ob1)
(blue ob1)
(on ob2 rtable)
(block ob2)
(blue ob2)
(on ob3 rtable)
(block ob3)
(blue ob3)
(on ob4 rtable)
(block ob4)
(blue ob4)
(on ob5 rtable)
(block ob5)
(blue ob5)
(on ob6 rtable)
(block ob6)
(blue ob6)
(on ob7 rtable)
(block ob7)
(blue ob7)
(on ob8 rtable)
(block ob8)
(blue ob8)
(on ob9 rtable)
(block ob9)
(blue ob9)
(table rtable)
(region rtable)
(hfree))
(:goal (and (holding or1)))
)