(define (problem Clutter_2)
(:domain clutter)
(:objects or1 ob0 ob1 rred rblue rtable)
(:init (on or1 rtable)
(block or1)
(red or1)
(on ob0 rtable)
(block ob0)
(blue ob0)
(on ob1 rtable)
(block ob1)
(blue ob1)
(table rtable)
(region rtable)
(hfree))
(:goal (and (holding or1)))
)