(define (problem sort_3_2_1)
(:domain sort)
(:objects or0 or1 ob0 rred rblue rtable)
(:init (on or0 rtable)
(block or0)
(red or0)
(on or1 rtable)
(block or1)
(red or1)
(on ob0 rtable)
(block ob0)
(blue ob0)
(table rtable)
(redregion rred)
(blueregion rblue)
(region rtable)
(region rred)
(region rblue)
(hfree))
(:goal (and (on or0 rred) (on or1 rred) (on ob0 rblue)))
)