(define (problem sort_3_0_3)
(:domain sort)
(:objects ob0 ob1 ob2 rred rblue rtable)
(:init (on ob0 rtable)
(block ob0)
(blue ob0)
(on ob1 rtable)
(block ob1)
(blue ob1)
(on ob2 rtable)
(block ob2)
(blue ob2)
(table rtable)
(redregion rred)
(blueregion rblue)
(region rtable)
(region rred)
(region rblue)
(hfree))
(:goal (and (on ob0 rblue) (on ob1 rblue) (on ob2 rblue)))
)