(define (problem sort_2_0_2)
(:domain sort)
(:objects ob0 ob1 rred rblue rtable)
(:init (on ob0 rtable)
(block ob0)
(blue ob0)
(on ob1 rtable)
(block ob1)
(blue ob1)
(table rtable)
(redregion rred)
(blueregion rblue)
(region rtable)
(region rred)
(region rblue)
(hfree))
(:goal (and (on ob0 rblue) (on ob1 rblue)))
)