(define (problem sort_6_6_0)
(:domain sort)
(:objects or0 or1 or2 or3 or4 or5 rred rblue rtable)
(:init (on or0 rtable)
(block or0)
(red or0)
(on or1 rtable)
(block or1)
(red or1)
(on or2 rtable)
(block or2)
(red or2)
(on or3 rtable)
(block or3)
(red or3)
(on or4 rtable)
(block or4)
(red or4)
(on or5 rtable)
(block or5)
(red or5)
(table rtable)
(redregion rred)
(blueregion rblue)
(region rtable)
(region rred)
(region rblue)
(hfree))
(:goal (and (on or0 rred) (on or1 rred) (on or2 rred) (on or3 rred) (on or4 rred) (on or5 rred)))
)