(define (problem sort_18_9_9)
(:domain sort)
(:objects or0 or1 or2 or3 or4 or5 or6 or7 or8 ob0 ob1 ob2 ob3 ob4 ob5 ob6 ob7 ob8 rred rblue rtable)
(:init (on or0 rtable)
(block or0)
(red or0)
(on or1 rtable)
(block or1)
(red or1)
(on or2 rtable)
(block or2)
(red or2)
(on or3 rtable)
(block or3)
(red or3)
(on or4 rtable)
(block or4)
(red or4)
(on or5 rtable)
(block or5)
(red or5)
(on or6 rtable)
(block or6)
(red or6)
(on or7 rtable)
(block or7)
(red or7)
(on or8 rtable)
(block or8)
(red or8)
(on ob0 rtable)
(block ob0)
(blue ob0)
(on ob1 rtable)
(block ob1)
(blue ob1)
(on ob2 rtable)
(block ob2)
(blue ob2)
(on ob3 rtable)
(block ob3)
(blue ob3)
(on ob4 rtable)
(block ob4)
(blue ob4)
(on ob5 rtable)
(block ob5)
(blue ob5)
(on ob6 rtable)
(block ob6)
(blue ob6)
(on ob7 rtable)
(block ob7)
(blue ob7)
(on ob8 rtable)
(block ob8)
(blue ob8)
(table rtable)
(redregion rred)
(blueregion rblue)
(region rtable)
(region rred)
(region rblue)
(hfree))
(:goal (and (on or0 rred) (on or1 rred) (on or2 rred) (on or3 rred) (on or4 rred) (on or5 rred) (on or6 rred) (on or7 rred) (on or8 rred) (on ob0 rblue) (on ob1 rblue) (on ob2 rblue) (on ob3 rblue) (on ob4 rblue) (on ob5 rblue) (on ob6 rblue) (on ob7 rblue) (on ob8 rblue)))
)