(define (problem sort_0_0_0)
(:domain sort)
(:objects rred rblue rtable)
(:init (table rtable)
(redregion rred)
(blueregion rblue)
(region rtable)
(region rred)
(region rblue)
(hfree))
(:goal (and ))
)