(define (problem sort_8_5_3)
(:domain sort)
(:objects or0 or1 or2 or3 or4 ob0 ob1 ob2 rred rblue rtable)
(:init (on or0 rtable)
(block or0)
(red or0)
(on or1 rtable)
(block or1)
(red or1)
(on or2 rtable)
(block or2)
(red or2)
(on or3 rtable)
(block or3)
(red or3)
(on or4 rtable)
(block or4)
(red or4)
(on ob0 rtable)
(block ob0)
(blue ob0)
(on ob1 rtable)
(block ob1)
(blue ob1)
(on ob2 rtable)
(block ob2)
(blue ob2)
(table rtable)
(redregion rred)
(blueregion rblue)
(region rtable)
(region rred)
(region rblue)
(hfree))
(:goal (and (on or0 rred) (on or1 rred) (on or2 rred) (on or3 rred) (on or4 rred) (on ob0 rblue) (on ob1 rblue) (on ob2 rblue)))
)