(define (problem sort_1_0_1)
(:domain sort)
(:objects ob0 rred rblue rtable)
(:init (on ob0 rtable)
(block ob0)
(blue ob0)
(table rtable)
(redregion rred)
(blueregion rblue)
(region rtable)
(region rred)
(region rblue)
(hfree))
(:goal (and (on ob0 rblue)))
)