(define (problem sort_1_1_0)
(:domain sort)
(:objects or0 rred rblue rtable)
(:init (on or0 rtable)
(block or0)
(red or0)
(table rtable)
(redregion rred)
(blueregion rblue)
(region rtable)
(region rred)
(region rblue)
(hfree))
(:goal (and (on or0 rred)))
)