(define (problem carry_1_1)
(:domain carry)
(:objects obj0 slot0 src dest c)
(:init (on obj0 src)
(block obj0)
(slot slot0)
(src_region src)
(dest_region dest)
(container c)
(region c)
(region dest)
(region src)
(canmove dest src)
(canmove src dest)
(at src)
(at c)
(hfree)
(on c src))
(:goal (and (on obj0 dest)))
)