(define (problem carry_2_2)
(:domain carry)
(:objects obj0 obj1 slot0 slot1 src dest c)
(:init (on obj0 src)
(block obj0)
(on obj1 src)
(block obj1)
(slot slot0)
(slot slot1)
(src_region src)
(dest_region dest)
(container c)
(region c)
(region dest)
(region src)
(canmove dest src)
(canmove src dest)
(at src)
(at c)
(hfree)
(on c src))
(:goal (and (on obj0 dest) (on obj1 dest)))
)