(define (problem carry_3_17)
(:domain carry)
(:objects obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 obj14 obj15 obj16 slot0 slot1 slot2 src dest c)
(:init (on obj0 src)
(block obj0)
(on obj1 src)
(block obj1)
(on obj2 src)
(block obj2)
(on obj3 src)
(block obj3)
(on obj4 src)
(block obj4)
(on obj5 src)
(block obj5)
(on obj6 src)
(block obj6)
(on obj7 src)
(block obj7)
(on obj8 src)
(block obj8)
(on obj9 src)
(block obj9)
(on obj10 src)
(block obj10)
(on obj11 src)
(block obj11)
(on obj12 src)
(block obj12)
(on obj13 src)
(block obj13)
(on obj14 src)
(block obj14)
(on obj15 src)
(block obj15)
(on obj16 src)
(block obj16)
(slot slot0)
(slot slot1)
(slot slot2)
(src_region src)
(dest_region dest)
(container c)
(region c)
(region dest)
(region src)
(canmove dest src)
(canmove src dest)
(at src)
(at c)
(hfree)
(on c src))
(:goal (and (on obj0 dest) (on obj1 dest) (on obj2 dest) (on obj3 dest) (on obj4 dest) (on obj5 dest) (on obj6 dest) (on obj7 dest) (on obj8 dest) (on obj9 dest) (on obj10 dest) (on obj11 dest) (on obj12 dest) (on obj13 dest) (on obj14 dest) (on obj15 dest) (on obj16 dest)))
)